export default  {
    CHANGE_RAW_IMAGE_DATA: 'CHANGE_RAW_IMAGE_DATA',
    IMAGE_ANALYZED: 'IMAGE_ANALYZED',
    RETAKE_IMAGE: 'RETAKE_IMAGE',
    LOAD_ANALYZE_ATTEMPT: 'LOAD_ANALYZE_ATTEMPT',
    LOAD_ANALYZE_SUCCESS: 'LOAD_ANALYZE_SUCCESS',
    LOAD_ANALYZE_FAILURE: 'LOAD_ANALYZE_FAILURE',
    SET_INPUT_MODE: 'SET_INPUT_MODE'
}